version: "3"
services:
  react-front:
    image: react-front:latest
    container_name: react-front
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - "./application:/app"
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    command: npm start

